# Set this to true to automatically assign skin to head. Set to false if you want everyone to drop steve heads.
player-skin: true
# Set this to true if you want to enable the rename recipe.
rename-enabled: false
# Set the item here for the rename recipe. Defaukt is 339 which is paper. Rename the item in an anvil first.
rename-item: 339
# The % chance for a player to drop their head. Integer between 0 and 100.
drop-chance: 50
# Valid death types for a player to drop head.
death-types:  
  - PVP
  - ALL
# Valid item to cause player drop head. (Item in hand of attacker)
items-required:
  - ANY
  - 276
# Sneak punch a skull to see who it belonged to.
sneak-punch-info: true
message: '&eThis head once belonged to &c%%NAME%%&e.'
# Options for zombies to drop heads.
zombie-heads:  
  drop-chance: 0
  items-required:
  - ANY
  - 276
  message: '&eThis head once belonged to a hungry &cZombie&e.'
# Options for skeletons to drop heads.
skeleton-heads:
  drop-chance: 0
  items-required:
  - ANY
  - 276
  message: '&eThis head once belonged to a &cSkeleton&e.'
# Options for creepers to drop heads.
creeper-heads:  
  drop-chance: 0
  items-required:
  - ANY
  - 276
  message: '&eThis head once belonged to an angry &cCreeper&e.'
# Nothing to see here.
debug-enabled: false  
# Custom skulls
# Options for spiders to drop heads.
spider-heads:  
  drop-chance: 0
  items-required:
  - ANY
  - 276
  skin: Kelevra_V
  message: '&eThis head once belonged to a hairy &cSpider&e.'
  # Options for endermen to drop heads.
enderman-heads:  
  drop-chance: 0
  items-required:
  - ANY
  - 276
  skin: Violit
  message: '&eThis head once belonged to a confused &cEnderman&e.'
  # Options for blazes to drop heads. 
blaze-heads:  
  drop-chance: 0
  items-required:
  - ANY
  - 276
  skin: Blaze_Head
  message: '&eThis head once belonged to a fiery &cBlaze&e.'
wither-heads:  
  message: '&eThis head once belonged to a withered &cWither&e.'